# Laboratorio 3.1 - Amazon SageMaker: Creación e importación de datos

**Nombre completo:** Richard Santiago Caicedo Toro

## Objetivo
Crear el entorno de trabajo en Amazon SageMaker Studio e importar un dataset para su
posterior análisis (EDA) y preprocesamiento.

## Explicación de la tarea
En este notebook se documenta el proceso de: (1) verificación del entorno de SageMaker,
(2) importación de librerías, (3) carga del dataset desde su fuente (S3, URL pública o
archivo local) y (4) una primera inspección básica de su estructura.

## 1. Importar librerías necesarias

In [7]:
from pathlib import Path

import numpy as np
import pandas as pd

print("pandas:", pd.__version__)
print("numpy:", np.__version__)
print("Modo local: SageMaker SDK no requerido")

pandas: 3.0.5
numpy: 2.4.3
Modo local: SageMaker SDK no requerido

## 2. Configurar la sesión de SageMaker (opcional si se trabaja con S3)

Si el dataset se va a subir/leer desde un bucket S3 asociado al Learner Lab, se inicializa
la sesión y se obtiene el rol de ejecución.

In [8]:
# session = sagemaker.Session()
# role = sagemaker.get_execution_role()
# bucket = session.default_bucket()
# print("Bucket por defecto:", bucket)

## 3. Cargar el dataset

Reemplaza la ruta/URL por la fuente real del dataset que estás usando en el laboratorio.

In [9]:
data_path = Path("data/dataset.csv")
if not data_path.exists():
    data_path = Path("../data/dataset.csv")

if not data_path.exists():
    raise FileNotFoundError("No se encontró data/dataset.csv ni ../data/dataset.csv")

df = pd.read_csv(data_path)
print(f"Dataset cargado desde: {data_path}")
df.head()

Dataset cargado desde: ..\data\dataset.csv

,student_id,age,city,study_hours,attendance,performance_level,final_score
0,1,20,Bogota,8.0,92.0,alto,4.6
1,2,21,Medellin,5.0,85.0,medio,3.8
2,3,19,Cali,3.0,72.0,bajo,2.9
3,4,22,Bogota,7.0,88.0,medio,4.1
4,5,20,Cartagena,2.0,65.0,bajo,2.5

## 4. Inspección inicial de la estructura del dataset

In [10]:
print("Dimensiones (filas, columnas):", df.shape)
df.info()

Dimensiones (filas, columnas): (15, 7)
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   student_id         15 non-null     int64
 1   age                15 non-null     int64
 2   city               15 non-null     str
 3   study_hours        14 non-null     float64
 4   attendance         14 non-null     float64
 5   performance_level  15 non-null     str
 6   final_score        15 non-null     float64
dtypes: float64(3), int64(2), str(2)
memory usage: 972.0 bytes

In [11]:
df.head(10)

,student_id,age,city,study_hours,attendance,performance_level,final_score
0,1,20,Bogota,8.0,92.0,alto,4.6
1,2,21,Medellin,5.0,85.0,medio,3.8
2,3,19,Cali,3.0,72.0,bajo,2.9
3,4,22,Bogota,7.0,88.0,medio,4.1
4,5,20,Cartagena,2.0,65.0,bajo,2.5
5,6,23,Medellin,9.0,96.0,alto,4.8
6,7,21,Cali,6.0,81.0,medio,3.7
7,8,20,Bogota,4.0,78.0,medio,3.4
8,9,24,Cartagena,1.0,59.0,bajo,2.1
9,10,22,Medellin,8.0,90.0,alto,4.5

In [12]:
df.dtypes

student_id             int64
age                    int64
city                     str
study_hours          float64
attendance           float64
performance_level        str
final_score          float64
dtype: object